name: Jekyll site CI

on:
  push:
    branches: [ repo-sync ]
  pull_request:
    branches: [ repo-sync ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
